version: '2'
services:
   metjekindnaarbuiten-spring-boot-docker:
      image: marinusgeuze/metjekindnaarbuiten-spring-boot-docker
      ports:
         - "80:8080"
      depends_on:
         - postgres
   postgres:
      image: postgres
      ports:
         - "5432:5432"
      environment:
         - POSTGRES_PASSWORD=mysecretpassword